# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Loop-Kqueue
version:      0.02
version_from: Kqueue.pm
installdirs:  site
requires:
    POE:                           0.3009

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
